import type { ClubMock, FavoriteBook, UserProfile } from "./types";

export const bookCatalog: FavoriteBook[] = [
  { id: "fundacion",        title: "Fundación",                          author: "Isaac Asimov",           cover: "/images/books/dune.jpg",   color: "blue" },
  { id: "neuromante",       title: "Neuromante",                         author: "William Gibson",          cover: "/images/books/1984.jpg",   color: "slate" },
  { id: "solaris",          title: "Solaris",                            author: "Stanislaw Lem",           cover: "/images/books/hobbit.jpg", color: "teal" },
  { id: "dune",             title: "Dune",                               author: "Frank Herbert",           cover: "/images/books/dune.jpg",   color: "amber" },
  { id: "1984",             title: "1984",                               author: "George Orwell",           cover: "/images/books/1984.jpg",   color: "zinc" },
  { id: "crimen-castigo",   title: "Crimen y castigo",                   author: "Fiódor Dostoievski",      cover: "/images/books/1984.jpg",   color: "red" },
  { id: "madame-bovary",    title: "Madame Bovary",                      author: "Gustave Flaubert",        cover: "/images/books/hobbit.jpg", color: "rose" },
  { id: "gatsby",           title: "El gran Gatsby",                     author: "F. Scott Fitzgerald",     cover: "/images/books/1984.jpg",   color: "emerald" },
  { id: "terramar",         title: "Terramar",                           author: "Ursula K. Le Guin",       cover: "/images/books/hobbit.jpg", color: "cyan" },
  { id: "nombre-viento",    title: "El nombre del viento",               author: "Patrick Rothfuss",        cover: "/images/books/dune.jpg",   color: "indigo" },
  { id: "nacidos-bruma",    title: "Nacidos de la bruma",                author: "Brandon Sanderson",       cover: "/images/books/1984.jpg",   color: "stone" },
  { id: "hobbit",           title: "El Hobbit",                          author: "J.R.R. Tolkien",          cover: "/images/books/hobbit.jpg", color: "green" },
  { id: "hyperion",         title: "Hyperion",                           author: "Dan Simmons",             cover: "/images/books/dune.jpg",   color: "violet" },
  { id: "le-guin-oscuridad",title: "La mano izquierda de la oscuridad", author: "Ursula K. Le Guin",       cover: "/images/books/1984.jpg",   color: "sky" },
  { id: "children-time",    title: "Children of Time",                   author: "Adrian Tchaikovsky",      cover: "/images/books/hobbit.jpg", color: "lime" },
  { id: "rayuela",          title: "Rayuela",                            author: "Julio Cortázar",          cover: "/images/books/1984.jpg",   color: "orange" },
  { id: "pedro-paramo",     title: "Pedro Páramo",                       author: "Juan Rulfo",              cover: "/images/books/hobbit.jpg", color: "neutral" },
];

export const mockUsers: UserProfile[] = [
  {
    id: "elena-vidal",
    username: "@elena_vidal",
    name: "Elena Vidal",
    bio: "Lectora compulsiva y exploradora de universos de ciencia ficción. Asimov y Le Guin son mi bálsamo ante el caos del mundo real.",
    avatar: "https://i.pravatar.cc/160?img=5",
    favoriteBooks: [
      { id: "dune",         title: "Dune",       author: "Frank Herbert",  cover: "/images/books/dune.jpg",   color: "amber" },
      { id: "fundacion",    title: "Fundación",  author: "Isaac Asimov",   cover: "/images/books/dune.jpg",   color: "blue" },
      { id: "1984",         title: "1984",        author: "George Orwell",  cover: "/images/books/1984.jpg",   color: "zinc" },
      { id: "solaris",      title: "Solaris",     author: "Stanislaw Lem",  cover: "/images/books/hobbit.jpg", color: "teal" },
    ],
    favoriteGenres: ["Ciencia ficción", "Distopía", "Space Opera"],
    clubIds: ["sci-fi-valencia"],
  },
  {
    id: "andres-vega",
    username: "@andres_vega",
    name: "Andrés Vega",
    bio: "Ensayista de guardia. Creo que la literatura clásica tiene respuesta para todo. Dostoievski > todo lo demás.",
    avatar: "https://i.pravatar.cc/160?img=3",
    favoriteBooks: [
      { id: "crimen-castigo", title: "Crimen y castigo", author: "Fiódor Dostoievski",    cover: "/images/books/1984.jpg",   color: "red" },
      { id: "gatsby",         title: "El gran Gatsby",   author: "F. Scott Fitzgerald",   cover: "/images/books/1984.jpg",   color: "emerald" },
      null,
      null,
    ],
    favoriteGenres: ["Literatura clásica", "Psicología narrativa"],
    clubIds: ["clasicos-madrid"],
  },
  {
    id: "paula-soler",
    username: "@paula_soler",
    name: "Paula Soler",
    bio: "Admin de Fantasía Online. Tolkien me cambió la vida a los 12 años y nunca me recuperé del todo.",
    avatar: "https://i.pravatar.cc/160?img=41",
    favoriteBooks: [null, null, null, null],
    favoriteGenres: ["Fantasía épica", "Worldbuilding", "Mitología"],
    clubIds: ["fantasia-online"],
  },
];

export function getUserById(id: string): UserProfile | undefined {
  return mockUsers.find((u) => u.id === id);
}

export function getAllCatalogBooks(): FavoriteBook[] {
  return bookCatalog;
}

export const clubs: ClubMock[] = [
  {
    id: "sci-fi-valencia",
    name: "SciFi Valencia",
    book: "Dune",
    bookCover: "/images/books/dune.jpg",
    author: "Frank Herbert",
    members: 12,
    adminId: "elena-vidal",
    membersList: [
      { id: "elena-vidal",  username: "@elena_vidal",  name: "Elena Vidal",   avatar: "https://i.pravatar.cc/96?img=5",  joinDate: "Enero 2022" },
      { id: "marco-ruiz",   username: "@marco_ruiz",   name: "Marco Ruiz",    avatar: "https://i.pravatar.cc/96?img=12", joinDate: "Febrero 2022" },
      { id: "sofia-llop",   username: "@sofia_llop",   name: "Sofía Llop",    avatar: "https://i.pravatar.cc/96?img=20", joinDate: "Febrero 2022" },
      { id: "diego-pons",   username: "@diego_pons",   name: "Diego Pons",    avatar: "https://i.pravatar.cc/96?img=33", joinDate: "Marzo 2022" },
      { id: "lucia-mas",    username: "@lucia_mas",    name: "Lucía Mas",     avatar: "https://i.pravatar.cc/96?img=44", joinDate: "Abril 2022" },
      { id: "nora-camps",   username: "@nora_camps",   name: "Nora Camps",    avatar: "https://i.pravatar.cc/96?img=47", joinDate: "Mayo 2022" },
      { id: "pablo-iborra", username: "@pablo_iborra", name: "Pablo Iborra",  avatar: "https://i.pravatar.cc/96?img=56", joinDate: "Junio 2022" },
      { id: "ines-ferrer",  username: "@ines_ferrer",  name: "Inés Ferrer",   avatar: "https://i.pravatar.cc/96?img=25", joinDate: "Julio 2022" },
      { id: "albert-mir",   username: "@albert_mir",   name: "Albert Mir",    avatar: "https://i.pravatar.cc/96?img=11", joinDate: "Agosto 2022" },
      { id: "celia-font",   username: "@celia_font",   name: "Celia Font",    avatar: "https://i.pravatar.cc/96?img=38", joinDate: "Octubre 2022" },
      { id: "raul-blasco",  username: "@raul_blasco",  name: "Raúl Blasco",   avatar: "https://i.pravatar.cc/96?img=51", joinDate: "Noviembre 2022" },
      { id: "marta-sanz",   username: "@marta_sanz",   name: "Marta Sanz",    avatar: "https://i.pravatar.cc/96?img=40", joinDate: "Enero 2023" },
    ],
    city: "Valencia",
    nextSession: "Jueves 19:00",
    description: "Club para lectores de ciencia ficción con foco en clásicos contemporáneos.",
    mode: "Presencial",
    shareRating: true,
    shareQuotes: true,
    stats: {
      booksRead: 42,
      attendance: "89%",
      genres: 6,
      quotes: 138,
    },
    upcomingEvents: [
      { date: "Jue 19:00", title: "Debate capítulos 5-8", location: "Russafa Lab" },
      { date: "Sáb 11:30", title: "Sesión abierta + invitados", location: "Biblioteca Central" },
      { date: "Mar 20:00", title: "Q&A de personajes", location: "Discord del club" },
    ],
    meetings: [
      {
        id: "scifi-m1",
        title: "Debate: Dune capítulos 1-5",
        date: "2026-03-06",
        time: "19:00",
        durationMinutes: 90,
        location: "Russafa Lab, Valencia",
        attendees: [
          { userId: "elena-vidal",  name: "Elena Vidal",  avatar: "https://i.pravatar.cc/96?img=5",  status: "si" },
          { userId: "marco-ruiz",   name: "Marco Ruiz",   avatar: "https://i.pravatar.cc/96?img=12", status: "si" },
          { userId: "sofia-llop",   name: "Sofía Llop",   avatar: "https://i.pravatar.cc/96?img=20", status: "si" },
          { userId: "diego-pons",   name: "Diego Pons",   avatar: "https://i.pravatar.cc/96?img=33", status: "no" },
          { userId: "lucia-mas",    name: "Lucía Mas",    avatar: "https://i.pravatar.cc/96?img=44", status: "si" },
        ],
      },
      {
        id: "scifi-m2",
        title: "Sesión abierta + invitados",
        date: "2026-03-19",
        time: "19:00",
        durationMinutes: 120,
        location: "Biblioteca Central, Valencia",
        attendees: [
          { userId: "elena-vidal",  name: "Elena Vidal",  avatar: "https://i.pravatar.cc/96?img=5",  status: "si" },
          { userId: "marco-ruiz",   name: "Marco Ruiz",   avatar: "https://i.pravatar.cc/96?img=12", status: "quizas" },
          { userId: "sofia-llop",   name: "Sofía Llop",   avatar: "https://i.pravatar.cc/96?img=20", status: "si" },
          { userId: "nora-camps",   name: "Nora Camps",   avatar: "https://i.pravatar.cc/96?img=47", status: "si" },
          { userId: "pablo-iborra", name: "Pablo Iborra", avatar: "https://i.pravatar.cc/96?img=56", status: "no" },
          { userId: "ines-ferrer",  name: "Inés Ferrer",  avatar: "https://i.pravatar.cc/96?img=25", status: "quizas" },
        ],
      },
      {
        id: "scifi-m3",
        title: "Q&A de personajes: Paul Atreides",
        date: "2026-03-27",
        time: "20:00",
        durationMinutes: 60,
        location: "Discord del club",
        attendees: [
          { userId: "elena-vidal",  name: "Elena Vidal",  avatar: "https://i.pravatar.cc/96?img=5",  status: "si" },
          { userId: "albert-mir",   name: "Albert Mir",   avatar: "https://i.pravatar.cc/96?img=11", status: "si" },
          { userId: "celia-font",   name: "Celia Font",   avatar: "https://i.pravatar.cc/96?img=38", status: "si" },
          { userId: "raul-blasco",  name: "Raúl Blasco",  avatar: "https://i.pravatar.cc/96?img=51", status: "quizas" },
        ],
      },
    ],
    readHistory: [
      {
        id: "fundacion",
        title: "Fundación",
        author: "Isaac Asimov",
        year: "1951",
        cover: "/images/books/dune.jpg",
        rating: 4.6,
        startDate: "3 de Enero, 2023",
        endDate: "28 de Febrero, 2023",
        memberRatings: [
          { name: "Elena", initial: "E", rating: 5 },
          { name: "Marco", initial: "M", rating: 4 },
          { name: "Sofia", initial: "S", rating: 5 },
        ],
        consensusVerdict: "Una obra maestra que redefine el concepto de civilización e historia. Lectura indispensable para cualquier amante de la ciencia ficción.",
        verdictSwatches: ["#c1121f", "#1b263b"],
        quotes: [
          { member: "Elena", text: "La violencia es el último recurso del incompetente.", page: "42" },
          { member: "Marco", text: "La ciencia ficción es la mitología de la era moderna y Fundación su épica definitiva.", page: "178" },
          { member: "Sofia", text: "El tiempo es el único recurso que no se puede recuperar, y Asimov lo sabe mejor que nadie.", page: "95" },
        ],
        totalHighlights: 12,
      },
      {
        id: "neuromante",
        title: "Neuromante",
        author: "William Gibson",
        year: "1984",
        cover: "/images/books/1984.jpg",
        rating: 4.4,
        startDate: "1 de Marzo, 2023",
        endDate: "10 de Abril, 2023",
        memberRatings: [
          { name: "Elena", initial: "E", rating: 4 },
          { name: "Marco", initial: "M", rating: 5 },
          { name: "Sofia", initial: "S", rating: 4 },
        ],
        consensusVerdict: "Visionaria y oscura, Neuromante inventa un lenguaje propio. Densa pero revolucionaria para entender el mundo digital.",
        verdictSwatches: ["#1b263b", "#4a5568"],
        quotes: [
          { member: "Elena", text: "El ciberespacio. Una alucinación consensual experimentada diariamente por billones de operadores.", page: "12" },
          { member: "Marco", text: "Gibson no predijo el futuro, lo creó con sus palabras antes de que existiera.", page: "201" },
          { member: "Sofia", text: "Hay una poesía oscura en cada página que te atrapa sin que te des cuenta.", page: "67" },
        ],
        totalHighlights: 9,
      },
      {
        id: "solaris",
        title: "Solaris",
        author: "Stanislaw Lem",
        year: "1961",
        cover: "/images/books/hobbit.jpg",
        rating: 4.2,
        startDate: "15 de Abril, 2023",
        endDate: "30 de Mayo, 2023",
        memberRatings: [
          { name: "Elena", initial: "E", rating: 4, avatar: "https://i.pravatar.cc/96?img=5", role: "Arquitectura" },
          { name: "Marco", initial: "M", rating: 4, avatar: "https://i.pravatar.cc/96?img=12", role: "Diseño interior" },
          { name: "Sofia", initial: "S", rating: 5, avatar: "https://i.pravatar.cc/96?img=20", role: "Tipografía" },
          { name: "Diego", initial: "D", rating: 5, avatar: "https://i.pravatar.cc/96?img=33", role: "Comunicación visual" },
          { name: "Lucia", initial: "L", rating: 4, avatar: "https://i.pravatar.cc/96?img=44", role: "Producto digital" },
          { name: "Nora", initial: "N", rating: 4, avatar: "https://i.pravatar.cc/96?img=47", role: "Arte editorial" },
          { name: "Pablo", initial: "P", rating: 5, avatar: "https://i.pravatar.cc/96?img=56", role: "Investigación" },
        ],
        consensusVerdict: "Un experimento filosófico disfrazado de novela. Plantea preguntas sobre la comunicación y lo desconocido que no tienen respuesta fácil.",
        verdictSwatches: ["#c1121f", "#8a98ad"],
        quotes: [
          { member: "Elena", text: "¿Qué buscamos realmente en el cosmos? ¿Un espejo de nosotros mismos?", page: "88" },
          { member: "Marco", text: "Lem demuestra que el mayor misterio no está en las estrellas sino en nuestra propia mente.", page: "134" },
          { member: "Sofia", text: "La impenetrabilidad del océano de Solaris es la impenetrabilidad del otro.", page: "55" },
          { member: "Diego", text: "Solaris no responde a nuestras preguntas: nos obliga a reformularlas desde cero.", page: "61" },
          { member: "Lucia", text: "El planeta parece vivo, pero quizá sea nuestra culpa buscar humanidad en lo desconocido.", page: "72" },
          { member: "Nora", text: "Cada visita a la estación demuestra que la memoria puede ser más aterradora que un monstruo.", page: "97" },
          { member: "Pablo", text: "Lem no escribe ciencia ficción de gadgets, escribe ciencia ficción de conciencia.", page: "121" },
          { member: "Elena", text: "La culpa de Kelvin pesa más que la gravedad de Solaris.", page: "144" },
          { member: "Marco", text: "La incapacidad de comunicarnos con Solaris es un retrato de nuestra incapacidad de comunicarnos entre nosotros.", page: "163" },
          { member: "Lucia", text: "La novela no busca explicar el océano: busca explicar nuestra obsesión por explicarlo todo.", page: "201" },
          { member: "Sofia", text: "Cuanto más observan Solaris, más se observan a sí mismos.", page: "219" },
        ],
        totalHighlights: 27,
      },
      {
        id: "dune",
        title: "Dune",
        author: "Frank Herbert",
        year: "1965",
        cover: "/images/books/dune.jpg",
        rating: 4.8,
        startDate: "5 de Junio, 2023",
        endDate: "31 de Julio, 2023",
        memberRatings: [
          { name: "Elena", initial: "E", rating: 5 },
          { name: "Marco", initial: "M", rating: 5 },
          { name: "Sofia", initial: "S", rating: 5 },
        ],
        consensusVerdict: "Una epopeya sin igual. Dune trasciende el género y se convierte en literatura universal. Cada relectura revela nuevas capas de significado.",
        verdictSwatches: ["#c1121f", "#1b263b"],
        quotes: [
          { member: "Elena", text: "No debo tener miedo. El miedo es el asesino de la mente. El miedo es la pequeña muerte que conduce a la extinción total.", page: "18" },
          { member: "Marco", text: "Herbert construye un universo tan rico y detallado que uno siente que podría vivir en él.", page: "312" },
          { member: "Sofia", text: "Quien controla la especia controla el universo. Una metáfora perfecta del poder y los recursos.", page: "147" },
        ],
        totalHighlights: 21,
      },
      {
        id: "1984-scifi",
        title: "1984",
        author: "George Orwell",
        year: "1949",
        cover: "/images/books/1984.jpg",
        rating: 4.7,
        startDate: "10 de Agosto, 2023",
        endDate: "20 de Septiembre, 2023",
        memberRatings: [
          { name: "Elena", initial: "E", rating: 5 },
          { name: "Marco", initial: "M", rating: 5 },
          { name: "Sofia", initial: "S", rating: 4 },
        ],
        consensusVerdict: "Profético y perturbador. Una lectura que cambia la forma en que ves el mundo. Más relevante hoy que cuando fue escrita.",
        verdictSwatches: ["#1b263b", "#c1121f"],
        quotes: [
          { member: "Elena", text: "La guerra es la paz. La libertad es la esclavitud. La ignorancia es la fuerza.", page: "6" },
          { member: "Marco", text: "Orwell vio con claridad meridiana hacia dónde podía llevar el totalitarismo. Un aviso que debemos escuchar.", page: "89" },
          { member: "Sofia", text: "Lo más aterrador no es el Gran Hermano, sino la gente que lo permite.", page: "203" },
        ],
        totalHighlights: 16,
      },
    ],
    wishList: [
      { title: "Hyperion", author: "Dan Simmons", cover: "/images/books/dune.jpg", votes: 18 },
      { title: "La mano izquierda de la oscuridad", author: "U. K. Le Guin", cover: "/images/books/1984.jpg", votes: 22 },
      { title: "Children of Time", author: "Adrian Tchaikovsky", cover: "/images/books/hobbit.jpg", votes: 15 },
    ],
  },
  {
    id: "clasicos-madrid",
    name: "Clásicos Madrid",
    book: "1984",
    bookCover: "/images/books/1984.jpg",
    author: "George Orwell",
    members: 14,
    adminId: "andres-vega",
    membersList: [
      { id: "andres-vega",    username: "@andres_vega",    name: "Andrés Vega",     avatar: "https://i.pravatar.cc/96?img=3",  joinDate: "Marzo 2021" },
      { id: "laura-gil",      username: "@laura_gil",      name: "Laura Gil",       avatar: "https://i.pravatar.cc/96?img=32", joinDate: "Abril 2021" },
      { id: "miguel-cano",    username: "@miguel_cano",    name: "Miguel Cano",     avatar: "https://i.pravatar.cc/96?img=14", joinDate: "Mayo 2021" },
      { id: "clara-rubio",    username: "@clara_rubio",    name: "Clara Rubio",     avatar: "https://i.pravatar.cc/96?img=21", joinDate: "Junio 2021" },
      { id: "javier-mora",    username: "@javier_mora",    name: "Javier Mora",     avatar: "https://i.pravatar.cc/96?img=8",  joinDate: "Julio 2021" },
      { id: "ana-fuentes",    username: "@ana_fuentes",    name: "Ana Fuentes",     avatar: "https://i.pravatar.cc/96?img=49", joinDate: "Septiembre 2021" },
      { id: "luis-santos",    username: "@luis_santos",    name: "Luis Santos",     avatar: "https://i.pravatar.cc/96?img=15", joinDate: "Octubre 2021" },
      { id: "belen-prieto",   username: "@belen_prieto",   name: "Belén Prieto",    avatar: "https://i.pravatar.cc/96?img=23", joinDate: "Noviembre 2021" },
      { id: "carlos-reyes",   username: "@carlos_reyes",   name: "Carlos Reyes",    avatar: "https://i.pravatar.cc/96?img=6",  joinDate: "Enero 2022" },
      { id: "teresa-alonso",  username: "@teresa_alonso",  name: "Teresa Alonso",   avatar: "https://i.pravatar.cc/96?img=35", joinDate: "Febrero 2022" },
      { id: "david-roman",    username: "@david_roman",    name: "David Román",     avatar: "https://i.pravatar.cc/96?img=17", joinDate: "Marzo 2022" },
      { id: "rosa-navarro",   username: "@rosa_navarro",   name: "Rosa Navarro",    avatar: "https://i.pravatar.cc/96?img=42", joinDate: "Junio 2022" },
      { id: "pablo-torres",   username: "@pablo_torres",   name: "Pablo Torres",    avatar: "https://i.pravatar.cc/96?img=57", joinDate: "Agosto 2022" },
      { id: "mia-delgado",    username: "@mia_delgado",    name: "Mía Delgado",     avatar: "https://i.pravatar.cc/96?img=29", joinDate: "Octubre 2022" },
    ],
    city: "Madrid",
    nextSession: "Domingo 11:30",
    description: "Sesiones de análisis literario de clásicos modernos y obras del siglo XX.",
    mode: "Presencial",
    shareRating: true,
    shareQuotes: false,
    stats: {
      booksRead: 57,
      attendance: "92%",
      genres: 9,
      quotes: 204,
    },
    upcomingEvents: [
      { date: "Dom 11:30", title: "Mesa redonda: poder y vigilancia", location: "La Fugitiva" },
      { date: "Mié 19:00", title: "Club de ensayo crítico", location: "Online" },
      { date: "Vie 18:00", title: "Lectura compartida de pasajes", location: "Conde Duque" },
    ],
    meetings: [
      {
        id: "clasicos-m1",
        title: "Mesa redonda: poder y vigilancia",
        date: "2026-03-01",
        time: "11:30",
        durationMinutes: 120,
        location: "La Fugitiva, Madrid",
        attendees: [
          { userId: "andres-vega",   name: "Andrés Vega",   avatar: "https://i.pravatar.cc/96?img=3",  status: "si" },
          { userId: "laura-gil",     name: "Laura Gil",     avatar: "https://i.pravatar.cc/96?img=32", status: "si" },
          { userId: "miguel-cano",   name: "Miguel Cano",   avatar: "https://i.pravatar.cc/96?img=14", status: "si" },
          { userId: "clara-rubio",   name: "Clara Rubio",   avatar: "https://i.pravatar.cc/96?img=21", status: "no" },
        ],
      },
      {
        id: "clasicos-m2",
        title: "Club de ensayo crítico",
        date: "2026-03-11",
        time: "19:00",
        durationMinutes: 90,
        location: "Online",
        attendees: [
          { userId: "andres-vega",   name: "Andrés Vega",   avatar: "https://i.pravatar.cc/96?img=3",  status: "si" },
          { userId: "javier-mora",   name: "Javier Mora",   avatar: "https://i.pravatar.cc/96?img=8",  status: "quizas" },
          { userId: "ana-fuentes",   name: "Ana Fuentes",   avatar: "https://i.pravatar.cc/96?img=49", status: "si" },
          { userId: "luis-santos",   name: "Luis Santos",   avatar: "https://i.pravatar.cc/96?img=15", status: "si" },
          { userId: "belen-prieto",  name: "Belén Prieto",  avatar: "https://i.pravatar.cc/96?img=23", status: "no" },
        ],
      },
      {
        id: "clasicos-m3",
        title: "Lectura compartida de pasajes",
        date: "2026-03-21",
        time: "18:00",
        durationMinutes: 90,
        location: "Conde Duque, Madrid",
        attendees: [
          { userId: "andres-vega",   name: "Andrés Vega",   avatar: "https://i.pravatar.cc/96?img=3",  status: "si" },
          { userId: "laura-gil",     name: "Laura Gil",     avatar: "https://i.pravatar.cc/96?img=32", status: "si" },
          { userId: "carlos-reyes",  name: "Carlos Reyes",  avatar: "https://i.pravatar.cc/96?img=6",  status: "quizas" },
          { userId: "teresa-alonso", name: "Teresa Alonso", avatar: "https://i.pravatar.cc/96?img=35", status: "si" },
          { userId: "david-roman",   name: "David Román",   avatar: "https://i.pravatar.cc/96?img=17", status: "si" },
        ],
      },
      {
        id: "clasicos-m4",
        title: "Cierre de 1984: debate final",
        date: "2026-03-29",
        time: "11:30",
        durationMinutes: 120,
        location: "La Fugitiva, Madrid",
        attendees: [
          { userId: "andres-vega",   name: "Andrés Vega",   avatar: "https://i.pravatar.cc/96?img=3",  status: "quizas" },
          { userId: "miguel-cano",   name: "Miguel Cano",   avatar: "https://i.pravatar.cc/96?img=14", status: "si" },
          { userId: "mia-delgado",   name: "Mía Delgado",   avatar: "https://i.pravatar.cc/96?img=29", status: "si" },
        ],
      },
    ],
    readHistory: [
      {
        id: "crimen-y-castigo",
        title: "Crimen y castigo",
        author: "Fiódor Dostoievski",
        year: "1866",
        cover: "/images/books/1984.jpg",
        rating: 4.7,
        startDate: "5 de Enero, 2023",
        endDate: "15 de Marzo, 2023",
        memberRatings: [
          { name: "Andrés", initial: "A", rating: 5 },
          { name: "Laura", initial: "L", rating: 5 },
          { name: "Miguel", initial: "M", rating: 4 },
        ],
        consensusVerdict: "Una inmersión brutal en la psicología humana. Dostoievski nos lleva al límite moral con una maestría narrativa sin igual.",
        verdictSwatches: ["#1b263b", "#c1121f"],
        quotes: [
          { member: "Andrés", text: "El dolor y el sufrimiento son inevitables para una mente lúcida y un corazón profundo.", page: "34" },
          { member: "Laura", text: "Raskólnikov no es un villano, es un espejo roto que refleja nuestras propias contradicciones.", page: "112" },
          { member: "Miguel", text: "Nadie escribe el crimen interior como Dostoievski. Una lectura que te persigue.", page: "278" },
        ],
        totalHighlights: 14,
      },
      {
        id: "madame-bovary",
        title: "Madame Bovary",
        author: "Gustave Flaubert",
        year: "1856",
        cover: "/images/books/hobbit.jpg",
        rating: 4.3,
        startDate: "20 de Marzo, 2023",
        endDate: "10 de Mayo, 2023",
        memberRatings: [
          { name: "Andrés", initial: "A", rating: 4 },
          { name: "Laura", initial: "L", rating: 5 },
          { name: "Miguel", initial: "M", rating: 4 },
        ],
        consensusVerdict: "Flaubert perfeccionó el realismo con esta novela. Emma Bovary es uno de los personajes más complejos y humanos de la literatura.",
        verdictSwatches: ["#c1121f", "#8a98ad"],
        quotes: [
          { member: "Andrés", text: "Emma buscaba en las novelas lo que la vida real no podía darle. ¿No hacemos todos lo mismo?", page: "56" },
          { member: "Laura", text: "Flaubert escribe con bisturí. Cada frase está calibrada para herir donde más duele.", page: "189" },
          { member: "Miguel", text: "La tragedia de Emma es la tragedia del idealismo aplastado por la mediocridad cotidiana.", page: "234" },
        ],
        totalHighlights: 8,
      },
      {
        id: "el-gran-gatsby",
        title: "El gran Gatsby",
        author: "F. Scott Fitzgerald",
        year: "1925",
        cover: "/images/books/1984.jpg",
        rating: 4.9,
        startDate: "15 de Mayo, 2023",
        endDate: "20 de Junio, 2023",
        memberRatings: [
          { name: "Andrés", initial: "A", rating: 5 },
          { name: "Laura", initial: "L", rating: 5 },
          { name: "Miguel", initial: "M", rating: 5 },
        ],
        consensusVerdict: "La novela americana por excelencia. Fitzgerald captura el sueño americano y su inevitable decadencia con una prosa de belleza inigualable.",
        verdictSwatches: ["#c1121f", "#1b263b"],
        quotes: [
          { member: "Andrés", text: "Así seguimos, botes contra la corriente, arrastrados sin cesar hacia el pasado.", page: "180" },
          { member: "Laura", text: "Gatsby no persigue a Daisy, persigue una versión de sí mismo que ya no existe.", page: "98" },
          { member: "Miguel", text: "La luz verde al final del muelle es la más hermosa metáfora del deseo imposible.", page: "22" },
        ],
        totalHighlights: 19,
      },
      {
        id: "1984-clasicos",
        title: "1984",
        author: "George Orwell",
        year: "1949",
        cover: "/images/books/1984.jpg",
        rating: 4.8,
        startDate: "1 de Julio, 2023",
        endDate: "20 de Agosto, 2023",
        memberRatings: [
          { name: "Andrés", initial: "A", rating: 5 },
          { name: "Laura", initial: "L", rating: 5 },
          { name: "Miguel", initial: "M", rating: 5 },
        ],
        consensusVerdict: "Vigente y necesaria. Una advertencia que se vuelve más urgente con cada año que pasa. Orwell escribió el manual del totalitarismo para que no lo olvidemos.",
        verdictSwatches: ["#1b263b", "#c1121f"],
        quotes: [
          { member: "Andrés", text: "El poder no es un medio, es un fin en sí mismo. Orwell entendió esto mejor que nadie.", page: "217" },
          { member: "Laura", text: "Doblepensar: mantener dos opiniones contradictorias simultáneamente. Cuánto vemos eso hoy.", page: "44" },
          { member: "Miguel", text: "El cuarto 101 es lo más terrorífico de la literatura porque es diferente para cada lector.", page: "289" },
        ],
        totalHighlights: 22,
      },
      {
        id: "dune-clasicos",
        title: "Dune",
        author: "Frank Herbert",
        year: "1965",
        cover: "/images/books/dune.jpg",
        rating: 4.5,
        startDate: "1 de Septiembre, 2023",
        endDate: "31 de Octubre, 2023",
        memberRatings: [
          { name: "Andrés", initial: "A", rating: 4 },
          { name: "Laura", initial: "L", rating: 5 },
          { name: "Miguel", initial: "M", rating: 4 },
        ],
        consensusVerdict: "Un desafío fascinante para un club de clásicos. Dune tiene la densidad y la ambición de la gran literatura aunque sea ciencia ficción.",
        verdictSwatches: ["#c1121f", "#8a98ad"],
        quotes: [
          { member: "Andrés", text: "La ecología como política. Herbert anticipó debates medioambientales con décadas de antelación.", page: "78" },
          { member: "Laura", text: "El mesianismo de Paul Atreides es una crítica feroz al culto a los líderes carismáticos.", page: "445" },
          { member: "Miguel", text: "Leer Dune con ojos de clásico literario revela una arquitectura narrativa extraordinaria.", page: "156" },
        ],
        totalHighlights: 11,
      },
    ],
    wishList: [
      { title: "Rayuela", author: "Julio Cortázar", cover: "/images/books/1984.jpg", votes: 31 },
      { title: "Pedro Páramo", author: "Juan Rulfo", cover: "/images/books/hobbit.jpg", votes: 27 },
      { title: "La montaña mágica", author: "Thomas Mann", cover: "/images/books/dune.jpg", votes: 19 },
    ],
  },
  {
    id: "fantasia-online",
    name: "Fantasía Online",
    book: "El Hobbit",
    bookCover: "/images/books/hobbit.jpg",
    author: "J.R.R. Tolkien",
    members: 21,
    adminId: "paula-soler",
    membersList: [
      { id: "paula-soler",   username: "@paula_soler",   name: "Paula Soler",    avatar: "https://i.pravatar.cc/96?img=41", joinDate: "Septiembre 2020" },
      { id: "rafa-molina",   username: "@rafa_molina",   name: "Rafa Molina",    avatar: "https://i.pravatar.cc/96?img=18", joinDate: "Octubre 2020" },
      { id: "neus-climent",  username: "@neus_climent",  name: "Neus Climent",   avatar: "https://i.pravatar.cc/96?img=45", joinDate: "Noviembre 2020" },
      { id: "oriol-badia",   username: "@oriol_badia",   name: "Oriol Badia",    avatar: "https://i.pravatar.cc/96?img=9",  joinDate: "Diciembre 2020" },
      { id: "irene-puig",    username: "@irene_puig",    name: "Irene Puig",     avatar: "https://i.pravatar.cc/96?img=27", joinDate: "Enero 2021" },
      { id: "marc-coll",     username: "@marc_coll",     name: "Marc Coll",      avatar: "https://i.pravatar.cc/96?img=10", joinDate: "Febrero 2021" },
      { id: "julia-ferre",   username: "@julia_ferre",   name: "Julia Ferré",    avatar: "https://i.pravatar.cc/96?img=36", joinDate: "Marzo 2021" },
      { id: "sergi-pla",     username: "@sergi_pla",     name: "Sergi Pla",      avatar: "https://i.pravatar.cc/96?img=22", joinDate: "Abril 2021" },
      { id: "anna-roca",     username: "@anna_roca",     name: "Anna Roca",      avatar: "https://i.pravatar.cc/96?img=46", joinDate: "Mayo 2021" },
      { id: "gerard-vera",   username: "@gerard_vera",   name: "Gerard Vera",    avatar: "https://i.pravatar.cc/96?img=2",  joinDate: "Junio 2021" },
      { id: "laia-mas",      username: "@laia_mas",      name: "Laia Mas",       avatar: "https://i.pravatar.cc/96?img=37", joinDate: "Julio 2021" },
      { id: "arnau-pi",      username: "@arnau_pi",      name: "Arnau Pi",       avatar: "https://i.pravatar.cc/96?img=13", joinDate: "Agosto 2021" },
      { id: "marina-abad",   username: "@marina_abad",   name: "Marina Abad",    avatar: "https://i.pravatar.cc/96?img=43", joinDate: "Septiembre 2021" },
      { id: "jan-costa",     username: "@jan_costa",     name: "Jan Costa",      avatar: "https://i.pravatar.cc/96?img=4",  joinDate: "Octubre 2021" },
      { id: "berta-valls",   username: "@berta_valls",   name: "Berta Valls",    avatar: "https://i.pravatar.cc/96?img=34", joinDate: "Noviembre 2021" },
      { id: "pol-casas",     username: "@pol_casas",     name: "Pol Casas",      avatar: "https://i.pravatar.cc/96?img=16", joinDate: "Enero 2022" },
      { id: "ona-miro",      username: "@ona_miro",      name: "Ona Miró",       avatar: "https://i.pravatar.cc/96?img=48", joinDate: "Febrero 2022" },
      { id: "dani-riu",      username: "@dani_riu",      name: "Dani Riu",       avatar: "https://i.pravatar.cc/96?img=7",  joinDate: "Abril 2022" },
      { id: "cris-bosch",    username: "@cris_bosch",    name: "Cris Bosch",     avatar: "https://i.pravatar.cc/96?img=26", joinDate: "Junio 2022" },
      { id: "alex-font",     username: "@alex_font",     name: "Alex Font",      avatar: "https://i.pravatar.cc/96?img=52", joinDate: "Agosto 2022" },
      { id: "toni-prat",     username: "@toni_prat",     name: "Toni Prat",      avatar: "https://i.pravatar.cc/96?img=19", joinDate: "Octubre 2022" },
    ],
    city: "Online",
    nextSession: "Martes 20:00",
    description: "Comunidad distribuida para lecturas de fantasía épica y worldbuilding.",
    mode: "Online",
    shareRating: false,
    shareQuotes: false,
    stats: {
      booksRead: 36,
      attendance: "86%",
      genres: 5,
      quotes: 121,
    },
    upcomingEvents: [
      { date: "Mar 20:00", title: "Mapa de la Tierra Media", location: "Zoom" },
      { date: "Jue 21:00", title: "Taller de personajes", location: "Discord" },
      { date: "Sáb 17:00", title: "Club de fan art", location: "Miro board" },
    ],
    meetings: [
      {
        id: "fantasia-m1",
        title: "Mapa de la Tierra Media",
        date: "2026-03-03",
        time: "20:00",
        durationMinutes: 60,
        location: "https://zoom.us/j/fantasia-online",
        attendees: [
          { userId: "paula-soler",  name: "Paula Soler",  avatar: "https://i.pravatar.cc/96?img=41", status: "si" },
          { userId: "rafa-molina",  name: "Rafa Molina",  avatar: "https://i.pravatar.cc/96?img=18", status: "si" },
          { userId: "neus-climent", name: "Neus Climent", avatar: "https://i.pravatar.cc/96?img=45", status: "si" },
          { userId: "oriol-badia",  name: "Oriol Badia",  avatar: "https://i.pravatar.cc/96?img=9",  status: "no" },
          { userId: "irene-puig",   name: "Irene Puig",   avatar: "https://i.pravatar.cc/96?img=27", status: "si" },
          { userId: "marc-coll",    name: "Marc Coll",    avatar: "https://i.pravatar.cc/96?img=10", status: "quizas" },
        ],
      },
      {
        id: "fantasia-m2",
        title: "Taller de personajes",
        date: "2026-03-17",
        time: "21:00",
        durationMinutes: 90,
        location: "https://discord.gg/fantasia-online",
        attendees: [
          { userId: "paula-soler",  name: "Paula Soler",  avatar: "https://i.pravatar.cc/96?img=41", status: "si" },
          { userId: "julia-ferre",  name: "Julia Ferré",  avatar: "https://i.pravatar.cc/96?img=36", status: "si" },
          { userId: "sergi-pla",    name: "Sergi Pla",    avatar: "https://i.pravatar.cc/96?img=22", status: "quizas" },
          { userId: "anna-roca",    name: "Anna Roca",    avatar: "https://i.pravatar.cc/96?img=46", status: "si" },
          { userId: "gerard-vera",  name: "Gerard Vera",  avatar: "https://i.pravatar.cc/96?img=2",  status: "si" },
        ],
      },
      {
        id: "fantasia-m3",
        title: "Club de fan art",
        date: "2026-03-25",
        time: "17:00",
        durationMinutes: 120,
        location: "https://miro.com/app/board/fantasia-fanart",
        attendees: [
          { userId: "paula-soler",  name: "Paula Soler",  avatar: "https://i.pravatar.cc/96?img=41", status: "si" },
          { userId: "laia-mas",     name: "Laia Mas",     avatar: "https://i.pravatar.cc/96?img=37", status: "si" },
          { userId: "arnau-pi",     name: "Arnau Pi",     avatar: "https://i.pravatar.cc/96?img=13", status: "no" },
          { userId: "marina-abad",  name: "Marina Abad",  avatar: "https://i.pravatar.cc/96?img=43", status: "quizas" },
          { userId: "berta-valls",  name: "Berta Valls",  avatar: "https://i.pravatar.cc/96?img=34", status: "si" },
        ],
      },
    ],
    readHistory: [
      {
        id: "terramar",
        title: "Terramar",
        author: "Ursula K. Le Guin",
        year: "1968",
        cover: "/images/books/hobbit.jpg",
        rating: 4.6,
        startDate: "10 de Enero, 2023",
        endDate: "5 de Marzo, 2023",
        memberRatings: [
          { name: "Paula", initial: "P", rating: 5 },
          { name: "Rafa", initial: "R", rating: 4 },
          { name: "Neus", initial: "N", rating: 5 },
        ],
        consensusVerdict: "Le Guin construye mundos con una humanidad desbordante. Terramar es fantasía filosófica del más alto nivel.",
        verdictSwatches: ["#c1121f", "#4a7c59"],
        quotes: [
          { member: "Paula", text: "Los nombres tienen poder. Le Guin lo sabía y por eso cada nombre en Terramar resuena.", page: "30" },
          { member: "Rafa", text: "Una fantasía que no necesita guerras ni héroes tradicionales para ser épica.", page: "112" },
          { member: "Neus", text: "Ged aprende que el mayor enemigo siempre es uno mismo. Una lección universal.", page: "87" },
        ],
        totalHighlights: 10,
      },
      {
        id: "el-nombre-del-viento",
        title: "El nombre del viento",
        author: "Patrick Rothfuss",
        year: "2007",
        cover: "/images/books/dune.jpg",
        rating: 4.8,
        startDate: "15 de Marzo, 2023",
        endDate: "20 de Mayo, 2023",
        memberRatings: [
          { name: "Paula", initial: "P", rating: 5 },
          { name: "Rafa", initial: "R", rating: 5 },
          { name: "Neus", initial: "N", rating: 5 },
        ],
        consensusVerdict: "Rothfuss reinventó la fantasía épica. La prosa es de una belleza inusual para el género y Kvothe es el héroe más fascinante de la fantasía moderna.",
        verdictSwatches: ["#c1121f", "#1b263b"],
        quotes: [
          { member: "Paula", text: "Llamé a mi dolor Denna para poder al menos ponerle un nombre.", page: "667" },
          { member: "Rafa", text: "El sistema de magia de la Simpatía es el más lógico y consistente de toda la literatura fantástica.", page: "234" },
          { member: "Neus", text: "Rothfuss escribe sobre música de tal manera que puedes escucharla en tu cabeza.", page: "178" },
        ],
        totalHighlights: 18,
      },
      {
        id: "nacidos-de-la-bruma",
        title: "Nacidos de la bruma",
        author: "Brandon Sanderson",
        year: "2006",
        cover: "/images/books/1984.jpg",
        rating: 4.4,
        startDate: "1 de Junio, 2023",
        endDate: "20 de Julio, 2023",
        memberRatings: [
          { name: "Paula", initial: "P", rating: 4 },
          { name: "Rafa", initial: "R", rating: 5 },
          { name: "Neus", initial: "N", rating: 4 },
        ],
        consensusVerdict: "Sanderson demuestra que el worldbuilding sistemático puede ser apasionante. La Alomancia es el sistema de magia más original de la fantasía contemporánea.",
        verdictSwatches: ["#4a5568", "#c1121f"],
        quotes: [
          { member: "Paula", text: "Todo lo que soy, todo lo que tengo, todo lo que me importa, lo apostaré en esto.", page: "543" },
          { member: "Rafa", text: "Sanderson convierte cada batalla en un puzzle lógico. La magia tiene reglas y eso lo hace brillante.", page: "201" },
          { member: "Neus", text: "Vin es el arquetipo de heroína que la fantasía necesitaba y tardaba tanto en darnos.", page: "89" },
        ],
        totalHighlights: 13,
      },
      {
        id: "el-hobbit",
        title: "El Hobbit",
        author: "J.R.R. Tolkien",
        year: "1937",
        cover: "/images/books/hobbit.jpg",
        rating: 5.0,
        startDate: "1 de Agosto, 2023",
        endDate: "15 de Septiembre, 2023",
        memberRatings: [
          { name: "Paula", initial: "P", rating: 5 },
          { name: "Rafa", initial: "R", rating: 5 },
          { name: "Neus", initial: "N", rating: 5 },
        ],
        consensusVerdict: "El origen de todo. El Hobbit es perfecto: accesible, emocionante y portador de una mitología que cambió la literatura para siempre.",
        verdictSwatches: ["#c1121f", "#4a7c59"],
        quotes: [
          { member: "Paula", text: "En un agujero en el suelo vivía un hobbit. La primera frase más perfecta de la literatura fantástica.", page: "1" },
          { member: "Rafa", text: "Tolkien no inventó la fantasía, la fundó sobre bases mitológicas sólidas que todos los demás siguen.", page: "312" },
          { member: "Neus", text: "Bilbo es el héroe que todos podemos ser: alguien ordinario que descubre que es más de lo que creía.", page: "167" },
        ],
        totalHighlights: 25,
      },
      {
        id: "dune-fantasia",
        title: "Dune",
        author: "Frank Herbert",
        year: "1965",
        cover: "/images/books/dune.jpg",
        rating: 4.7,
        startDate: "1 de Octubre, 2023",
        endDate: "30 de Noviembre, 2023",
        memberRatings: [
          { name: "Paula", initial: "P", rating: 5 },
          { name: "Rafa", initial: "R", rating: 4 },
          { name: "Neus", initial: "N", rating: 5 },
        ],
        consensusVerdict: "Leer Dune desde la perspectiva de la fantasía épica revela su deuda con Tolkien y sus propias innovaciones. Un cruce de géneros extraordinario.",
        verdictSwatches: ["#c1121f", "#1b263b"],
        quotes: [
          { member: "Paula", text: "Arrakis es Mordor en el desierto: un lugar de poder y peligro que define a sus habitantes.", page: "88" },
          { member: "Rafa", text: "Los Fremen son los elfos del desierto: una cultura antigua con sabiduría que los foráneos no comprenden.", page: "203" },
          { member: "Neus", text: "Herbert y Tolkien comparten la obsesión por los idiomas construidos. El Fremen suena tan real como el élfico.", page: "45" },
        ],
        totalHighlights: 15,
      },
    ],
    wishList: [
      { title: "El priorato del naranjo", author: "Samantha Shannon", cover: "/images/books/hobbit.jpg", votes: 24 },
      { title: "La rueda del tiempo", author: "Robert Jordan", cover: "/images/books/dune.jpg", votes: 20 },
      { title: "La quinta estación", author: "N. K. Jemisin", cover: "/images/books/1984.jpg", votes: 17 },
    ],
  },
];

export function getClubById(id: string): ClubMock | undefined {
  return clubs.find((club) => club.id === id);
}

export function getBookRouteId(title: string): string {
  return encodeURIComponent(title.trim().toLowerCase());
}

function normalizeBookKey(value: string): string {
  try {
    return decodeURIComponent(value).trim().toLowerCase();
  } catch {
    return value.trim().toLowerCase();
  }
}

export function getBookById(clubId: string, bookId: string) {
  const club = getClubById(clubId);
  const bookKey = normalizeBookKey(bookId);
  return club?.readHistory.find(
    (book) => normalizeBookKey(book.id) === bookKey || normalizeBookKey(book.title) === bookKey
  );
}
