import type {
  ExploreClub,
  ExploreLibrary,
  ExploreLibraryMetricEvent,
  ExploreViewerMode,
} from "./types";

const AUTHENTICATED_USER_PREFERENCES = [
  "Ciencia ficcion",
  "Distopia",
  "Clasicos",
  "Filosofia",
  "Fantasia epica",
];

export const exploreClubs: ExploreClub[] = [
  {
    id: "tinta-roja-barracas",
    name: "Tinta Roja Barracas",
    mode: "Presencial",
    currentBook: "Rayuela",
    bookCover: "/images/books/dune.jpg",
    currentAuthor: "Julio Cortazar",
    members: 16,
    maxMembers: 20,
    city: "Barracas",
    address: "Montes de Oca 845, CABA",
    distanceKm: 1.1,
    categories: ["Clasicos", "Filosofia", "Novela contemporanea", "Literatura latinoamericana", "Ensayo"],
    createdAt: "2021-04-10",
    nextSession: "Jueves 19:30",
    description: "Lectura latinoamericana con debates en formato laboratorio editorial.",
  },
  {
    id: "sci-fi-sur",
    name: "Sci-Fi del Sur",
    mode: "Presencial",
    currentBook: "Fundacion",
    bookCover: "/images/books/dune.jpg",
    currentAuthor: "Isaac Asimov",
    members: 12,
    maxMembers: 12,
    city: "Parque Patricios",
    address: "Uspallata 1690, CABA",
    distanceKm: 1.4,
    categories: ["Ciencia ficcion", "Distopia", "Space opera", "Politica", "Tecnologia"],
    createdAt: "2020-07-12",
    nextSession: "Martes 20:00",
    description: "Grupo tecnico para lectores que disfrutan discutir sistemas politicos y tecnologia.",
  },
  {
    id: "ritmo-clasico-san-telmo",
    name: "Ritmo Clasico San Telmo",
    mode: "Presencial",
    currentBook: "Madame Bovary",
    bookCover: "/images/books/1984.jpg",
    currentAuthor: "Gustave Flaubert",
    members: 9,
    maxMembers: 12,
    city: "San Telmo",
    address: "Defensa 1215, CABA",
    distanceKm: 2,
    categories: ["Clasicos", "Ensayo", "Psicologia narrativa", "Narrativa francesa"],
    createdAt: "2019-05-22",
    nextSession: "Sabado 11:00",
    description: "Encuentros de lectura lenta y escritura de bitacoras criticas.",
  },
  {
    id: "callejon-distopico",
    name: "Callejon Distopico",
    mode: "Presencial",
    currentBook: "1984",
    bookCover: "/images/books/1984.jpg",
    currentAuthor: "George Orwell",
    members: 11,
    maxMembers: 14,
    city: "Almagro",
    address: "Medrano 320, CABA",
    distanceKm: 2,
    categories: ["Distopia", "Ciencia ficcion", "Politica", "Tecnologia", "Filosofia"],
    createdAt: "2023-01-15",
    nextSession: "Miercoles 19:00",
    description: "Club de debate para ficcion politica y narrativas de vigilancia.",
  },
  {
    id: "noche-fantastica-boedo",
    name: "Noche Fantastica Boedo",
    mode: "Presencial",
    currentBook: "El Hobbit",
    bookCover: "/images/books/hobbit.jpg",
    currentAuthor: "J.R.R. Tolkien",
    members: 8,
    maxMembers: 10,
    city: "Boedo",
    address: "Estados Unidos 3721, CABA",
    distanceKm: 2.4,
    categories: ["Fantasia epica", "Mitologia", "Aventura", "Worldbuilding"],
    createdAt: "2022-11-04",
    nextSession: "Viernes 20:30",
    description: "Mesa de worldbuilding y narrativa fantastica.",
  },
  {
    id: "cafe-filosofico-caballito",
    name: "Cafe Filosofico Caballito",
    mode: "Presencial",
    currentBook: "La nausea",
    bookCover: "/images/books/1984.jpg",
    currentAuthor: "Jean-Paul Sartre",
    members: 10,
    maxMembers: 10,
    city: "Caballito",
    address: "Av. Rivadavia 5501, CABA",
    distanceKm: 3,
    categories: ["Filosofia", "Ensayo", "Clasicos", "Existencialismo", "Politica"],
    createdAt: "2018-08-01",
    nextSession: "Domingo 17:00",
    description: "Debates de filosofia existencial aplicados a textos narrativos.",
  },
  {
    id: "sci-fi-transatlantico",
    name: "Sci-Fi Transatlantico",
    mode: "Online",
    currentBook: "Children of Time",
    bookCover: "/images/books/dune.jpg",
    currentAuthor: "Adrian Tchaikovsky",
    members: 24,
    maxMembers: 30,
    city: "Online",
    address: "Sala virtual - Zoom",
    distanceKm: 0,
    categories: ["Ciencia ficcion", "Space opera", "Biotecnologia", "Futurologia"],
    createdAt: "2019-03-15",
    nextSession: "Miercoles 22:00",
    description: "Comunidad hispana distribuida para sci-fi de alto concepto.",
  },
  {
    id: "distopia-discord",
    name: "Distopia en Discord",
    mode: "Online",
    currentBook: "Fahrenheit 451",
    bookCover: "/images/books/1984.jpg",
    currentAuthor: "Ray Bradbury",
    members: 30,
    maxMembers: 30,
    city: "Online",
    address: "Servidor privado - Discord",
    distanceKm: 0,
    categories: ["Distopia", "Ciencia ficcion", "Clasicos", "Politica", "Tecnologia"],
    createdAt: "2020-09-10",
    nextSession: "Lunes 21:00",
    description: "Formato sprint para lecturas cortas y debates rapidos.",
  },
  {
    id: "epica-colectiva",
    name: "Epica Colectiva",
    mode: "Online",
    currentBook: "Terramar",
    bookCover: "/images/books/hobbit.jpg",
    currentAuthor: "Ursula K. Le Guin",
    members: 18,
    maxMembers: 25,
    city: "Online",
    address: "Sala virtual - Google Meet",
    distanceKm: 0,
    categories: ["Fantasia epica", "Mitologia", "Filosofia", "Aventura", "Worldbuilding"],
    createdAt: "2021-02-03",
    nextSession: "Jueves 21:30",
    description: "Lecturas fantasticas con enfoque en estructura narrativa.",
  },
  {
    id: "canon-abierto",
    name: "Canon Abierto",
    mode: "Online",
    currentBook: "Pedro Paramo",
    bookCover: "/images/books/1984.jpg",
    currentAuthor: "Juan Rulfo",
    members: 14,
    maxMembers: 18,
    city: "Online",
    address: "Canal de voz - Jitsi",
    distanceKm: 0,
    categories: ["Clasicos", "Literatura latinoamericana", "Poesia", "Realismo magico", "Narrativa breve"],
    createdAt: "2018-12-01",
    nextSession: "Martes 19:30",
    description: "Lecturas de canon iberoamericano con curaduria por temporada.",
  },
];

export const exploreLibraries: ExploreLibrary[] = [
  {
    id: "libro-urbano",
    name: "Libro Urbano",
    address: "Av. Caseros 1780, CABA",
    phone: "+54 11 4231-2001",
    distanceKm: 0.5,
    geo: { lat: -34.6399, lng: -58.3912 },
  },
  {
    id: "la-pagina-sur",
    name: "La Pagina Sur",
    address: "Defensa 951, CABA",
    phone: "+54 11 4231-2002",
    distanceKm: 1.2,
    geo: { lat: -34.6188, lng: -58.3731 },
  },
  {
    id: "tinta-minima",
    name: "Tinta Minima",
    address: "Av. Independencia 2450, CABA",
    phone: "+54 11 4231-2003",
    distanceKm: 1.8,
    geo: { lat: -34.6222, lng: -58.3986 },
  },
  {
    id: "nodo-lectura",
    name: "Nodo Lectura",
    address: "Carlos Calvo 1602, CABA",
    phone: "+54 11 4231-2004",
    distanceKm: 2.3,
    geo: { lat: -34.6255, lng: -58.3854 },
  },
  {
    id: "estacion-capitulo",
    name: "Estacion Capitulo",
    address: "Av. Boedo 945, CABA",
    phone: "+54 11 4231-2005",
    distanceKm: 2.9,
    geo: { lat: -34.6333, lng: -58.4132 },
  },
  {
    id: "cuadra-editorial",
    name: "Cuadra Editorial",
    address: "Rivadavia 4200, CABA",
    phone: "+54 11 4231-2006",
    distanceKm: 3.4,
    geo: { lat: -34.6118, lng: -58.429 },
  },
];

export function getExploreViewerCategories(viewerMode: ExploreViewerMode): string[] {
  return viewerMode === "authenticated" ? AUTHENTICATED_USER_PREFERENCES : [];
}

export function getNearestLibraries(limit = 5): ExploreLibrary[] {
  return [...exploreLibraries]
    .sort((first, second) => first.distanceKm - second.distanceKm)
    .slice(0, limit);
}

export function createLibraryMetricEvent(
  libraryId: string,
  viewerMode: ExploreViewerMode,
  source: ExploreLibraryMetricEvent["source"],
): ExploreLibraryMetricEvent {
  return {
    id: `${libraryId}-${Date.now()}`,
    libraryId,
    viewerMode,
    source,
    createdAt: new Date().toISOString(),
  };
}
